clean:
	rm -f *.lo[a,f,l,t,g] *.bb[l,g] *.blg *.out *.nlo *.toc \
         *.aux *-blx.bib *.run.xml *.sw[op] *~ *.bib.bak *.bib.sav \
         *.fls *.fdb_latexmk *.md5 *.dpth *.run.xml *.auxlock *.bcf \
         *.acn *.acr *.alg *.glg *.glo *.gls *.ist \
         *_bibertool.bib
